config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/index'
  get 'search', to: 'home#search'
  get 'find_suggestions', to: 'home#find_suggestions'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
  def score
    hits * 0.8 + 1 / (0.1 + elapsed_days)
  end

  def elapsed_days
    (Search.last.updated_at.to_date - Date.today).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  NUMBER_OF_SUGGESTIONS = 5
  MAX_RANKING = 50

  def index
  end

  def find_suggestions
    query = sanitize(params[:search])
    top_ten_suggestions = find_top_ten(query)

    render json: build_json_response(top_ten_suggestions) 
  end

  def search
    @query = sanitize(params[:search_input])
    @top_ten_suggestions = find_top_ten(@query)

    # process search
    increase_hits(@query) || Search.create(text: @query)
  end

  private

  def increase_hits(query)
    search = Search.find_by_text(query)
    if search
      search.increment(:hits).save
    else
      false
    end
  end

  def sanitize(query)
    # sanitize query
    query.downcase!
    I18n.transliterate(query)
  end

  def find_top_ten(query)
    # find similar words 
    unprocessed_suggestions = Search.where("text LIKE :query", {:query => "%#{query}%"})
    # score, sort and limit results
    unprocessed_suggestions.sort {|min, max| max.score <=> min.score}.first(NUMBER_OF_SUGGESTIONS)
  end

  def build_json_response(results)
    results_list = []
    results.each do |word|
      results_list << {id: word.text, text: word.text}
    end
    {"results": results_list}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_results_list.html.erb
<p class="lead">Búsquedas relacionadas con <span class="font-weight-bold"><%= @query %></span></p>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Texto</th>
      <th scope="col">Hits</th>
      <th scope="col">Ultima busqueda</th>
      <th scope="col">Score</th>
    </tr>
  </thead>
  <tbody>
    <% @top_ten_suggestions.each do |suggestion| %>
      <tr 
        <% if @query == suggestion.text %>
            class="bg-success"  
          <% end %> >
          <th scope="row"><%= suggestion.text %></th>
          <td><%= suggestion.hits %></td>
          <td><%= suggestion.elapsed_days %> dias atras</td>
          <td><%= suggestion.score.round(4) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container text-center">
    <h1 class="display-4">Auto-suggest-me</h1>
    <p class="lead">un buscador que utiliza un Agente Inteligente (IA) para auto-suggestions de palabras</p>
    <p class="lead">basado en hits y última fecha de búsqueda</p>
  </div>
</div>

<div class="card mx-auto w-50">
  <div class="card-body w-100">
    <%= form_tag("/search", method: "get", remote: true) do %>
      <div class="form-group">
        <%= select_tag(:search_input, "", class: "w-75 js-data-example-ajax") %>
        <%= submit_tag("Buscar", class: "btn btn-outline-warning") %>
      </div>
    <% end %>
  </div>
</div>

<div class="card mx-auto w-50 mt-5 results-card" style="display: none;">
  <div class="card-body w-100">
    <div class="search_result">
    </div>
  </div>
</div>

<script>
  $('#search_input').select2({
    // configuration
    placeholder: 'Ingrese su búsqueda',
    minimumInputLength: 1,
    tags: true,
    allowClear: true,
    selectOnClose: true,
    // ajax options
    ajax: {
      url: "<%= find_suggestions_path  %>",
      data: function (params) {
        var query = {
          search: params.term,
        }
        return query;
      }
    }
  });
</script>

app/views/home/search.js.erb
$('.results-card').show()
$('.search_result').html("<%= j  render partial: 'results_list' %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FundamentosFinal</title>
    <%= csrf_meta_tags %>
		
		<!-- bootstrap dependencies -->

		<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

		<!-- bootstrap  -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>